<?php
/**
 * @file
 */

include_once 'gbmarket_user.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function gbmarket_user_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gbmarket_user_form_user_register_form_alter(&$form, $form_state) {
  array_unshift($form['#validate'], 'gbmarket_user_user_register_form_validate');

  $form['subtitle'] = array(
    '#markup' => '<h3>' . t('No credit card needed!') . '</h3>',
    '#weight' => -20,
  );

  $form['account']['name']['#required'] = FALSE;
  $form['account']['name']['#access'] = FALSE;

  // The titles are hidden with CSS because they are used in the validation
  // error messages.
  $form['account']['mail']['#hint'] = $form['account']['mail']['#title'];
  $form['account']['mail']['#description'] = '';

  $form['account']['pass']['#type'] = 'password';
  $form['account']['pass']['#hint'] = t('Password');
  $form['account']['pass']['#title'] = t('Password');
  $form['account']['pass']['#description'] = '';

  $form['field_company'][LANGUAGE_NONE][0]['value']['#hint'] = $form['field_company'][LANGUAGE_NONE][0]['value']['#title'];

  $form['actions']['submit']['#prefix'] = '<span class="button">';
  $form['actions']['submit']['#suffix'] = '</span>';
  $form['actions']['submit']['#value'] = t('Start working');
}

/**
 * Validation callback for the user registration form.
 */
function gbmarket_user_user_register_form_validate($form, &$form_state) {
  $form_state['values']['name'] = $form_state['values']['mail'];
}