<?php
/**
 * @file
 * gbmarket_general.features.inc
 */

/**
 * Implements hook_fontyourface_features_default_font().
 */
function gbmarket_general_fontyourface_features_default_font() {
  return array(
    'Dosis normal normal' => array(
      'name' => 'Dosis normal normal',
      'enabled' => '1',
      'url' => 'http://localhost/#87b73e77d81c3e8b986dec610a25d088',
      'provider' => 'local_fonts',
      'css_selector' => 'h1, h2, h3, h4, h5, h6',
      'css_family' => 'Dosis',
      'css_style' => 'normal',
      'css_weight' => 'normal',
      'css_fallbacks' => '',
      'foundry' => '',
      'foundry_url' => '',
      'license' => '',
      'license_url' => '',
      'designer' => '',
      'designer_url' => '',
      'metadata' => 'a:2:{s:4:"path";s:68:"public://fontyourface/local_fonts/Dosis-normal-normal/stylesheet.css";s:8:"font_uri";a:4:{s:3:"eot";s:70:"public://fontyourface/local_fonts/Dosis-normal-normal/Dosis-Medium.eot";s:8:"truetype";s:70:"public://fontyourface/local_fonts/Dosis-normal-normal/Dosis-Medium.ttf";s:4:"woff";s:71:"public://fontyourface/local_fonts/Dosis-normal-normal/Dosis-Medium.woff";s:3:"svg";s:70:"public://fontyourface/local_fonts/Dosis-normal-normal/Dosis-Medium.svg";}}',
    ),
    'Neo Sans normal normal' => array(
      'name' => 'Neo Sans normal normal',
      'enabled' => '1',
      'url' => 'http://localhost/#b0bf605ce2d0bcb8804fbf40874aeaf5',
      'provider' => 'local_fonts',
      'css_selector' => '<none>',
      'css_family' => 'Neo Sans',
      'css_style' => 'normal',
      'css_weight' => 'normal',
      'css_fallbacks' => '',
      'foundry' => '',
      'foundry_url' => '',
      'license' => '',
      'license_url' => '',
      'designer' => '',
      'designer_url' => '',
      'metadata' => 'a:2:{s:4:"path";s:71:"public://fontyourface/local_fonts/Neo_Sans-normal-normal/stylesheet.css";s:8:"font_uri";a:4:{s:3:"eot";s:75:"public://fontyourface/local_fonts/Neo_Sans-normal-normal/Neo Sans Light.eot";s:8:"truetype";s:75:"public://fontyourface/local_fonts/Neo_Sans-normal-normal/Neo Sans Light.ttf";s:4:"woff";s:76:"public://fontyourface/local_fonts/Neo_Sans-normal-normal/Neo Sans Light.woff";s:3:"svg";s:75:"public://fontyourface/local_fonts/Neo_Sans-normal-normal/Neo Sans Light.svg";}}',
    ),
  );
}
