<?php

/**
 * @file
 * Provides Marketplace functionality on the gbmarket.
 */

/**
 * Implements hook_menu().
 */
function gbmarket_marketplace_menu() {
  $items = array();

  $items['module/%commerce_product'] = array(
    'title callback' => 'gbmarket_marketplace_module_title',
    'title arguments' => array(1),
    'page callback' => 'gbmarket_marketplace_module_view',
    'page arguments' => array(1),
    'access callback' => 'commerce_product_access',
    'access arguments' => array('view', 1),
  );

  return $items;
}

/**
 * Menu item title callback.
 *
 * @param $product
 *   The product object as loaded via menu loader.
 * @return
 *   A page title of the module.
 */
function gbmarket_marketplace_module_title($product) {
  return t('@title', array('@title' => $product->title));
}

/**
 * Displays a product (module).
 *
 * @param $product
 *   The product object as loaded via menu loader.
 * @return
 *   Rendered page of the module.
 */
function gbmarket_marketplace_module_view($product) {
  return drupal_render(entity_view('commerce_product', array($product), 'full'));
}

/**
* Implements hook_entity_info_alter().
*/
function gbmarket_marketplace_entity_info_alter(&$entity_info) {
  $entity_info['commerce_product']['view modes']['gallery'] = array(
    'label' => t('Gallery View'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_preprocess_entity().
 */
function gbmarket_marketplace_preprocess_entity(&$variables, $hook) {
  if ($variables['entity_type'] == 'commerce_product') {
    $variables['theme_hook_suggestions'][] = $variables['entity_type'] . '__gallery';
  }
}

/**
 * Implements hook_theme().
 */
function gbmarket_marketplace_theme($existing, $type, $theme, $path) {
  return array(
    'gallery' => array(
      'variables' => array('element' => null),
      'template' => 'commerce_product__gallery',
      'path' => drupal_get_path('module', 'gbmarket_marketplace') . '/templates',
    ),
  );
}

/**
 * Implements hook_commerce_product_uri().
 */
function gbmarket_marketplace_commerce_product_uri($product) {
  return array(
    'path' => 'module/' . $product->product_id,
  );
}

/**
 * Implements hook_views_api().
 */
function gbmarket_marketplace_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'gbmarket_marketplace') . '/includes/views',
  );
}
